baseURL = 'http://activemetro.org/'
languageCode = 'en-us'
title = 'Portland Metro Active Transit Advocates'
theme = 'hugo-xmin'

[menu]
[[menu.main]]
 name = "Home"
 url = ""
 weight = 1
[[menu.main]]
 name = "Learn"
 url = "learn/"
 weight = 2
[[menu.main]]
 name = "About"
 url = "about/"
 weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

